name: Node.js CI

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche `main`
  pull_request:
    branches:
      - main  # Déclenche le workflow à chaque pull request vers la branche `main`

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'un environnement Ubuntu pour exécuter le workflow

    steps:
    # 1. Checkout du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Node.js (version 16 dans cet exemple)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Vous pouvez adapter la version de Node.js à celle que vous utilisez

    # 3. Installer les dépendances
    - name: Install dependencies
      run: |
        npm install  # Installe toutes les dépendances définies dans package.json

    # 4. Exécuter les tests
    - name: Run tests
      run: |
        npm test  # Exécute les tests définis dans votre projet (assurez-vous que "test" est dans les scripts de package.json)

    # 5. Déployer (facultatif)
    # Si vous avez un déploiement à faire, vous pouvez ajouter un script pour cela. Exemple avec SSH:
    - name: Deploy to server
      run: |
        echo "Déploiement de l'application..."
        scp -r ./build user@server:/path/to/deploy  # Adaptez cette commande à votre serveur
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}  # Utilisation d'une clé privée sécurisée pour le déploiement
