name: CI/CD Pipeline

# Déclencheur pour le workflow (lors d'un push ou d'une pull request sur la branche main)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job pour l'intégration continue (compilation, tests)
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (si vous utilisez Node.js, sinon adaptez)
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Spécifiez la version Node.js à utiliser

      - name: Install dependencies
        run: npm install  # Remplacez par la commande appropriée pour votre projet (ex: pip install pour Python)

      - name: Run tests
        run: npm test  # Remplacez par la commande appropriée pour vos tests

  # Job pour le déploiement
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test  # Ce job attend la fin du job précédent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          echo "Déploiement de l'application..."
          # Ajoutez ici les étapes pour déployer sur votre serveur
          # Exemple: `scp -r ./build user@server:/path/to/deploy`



