name: Build and Push Docker image

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de l'image Ubuntu la plus récente
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Récupère le code source du dépôt

      - name: Log in to DockerHub
        uses: docker/login-action@v2  # Utilise l'action pour se connecter à DockerHub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilise le secret DOCKER_USERNAME
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utilise le secret DOCKER_PASSWORD

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .  # Construire l'image Docker

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Pousser l'image sur DockerHub


